eureka :
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
demo:  
  app: 
    name: WELCOME TO SPRING CLOUD SERVER .
insurance:
  provider:
         url: http://localhost:8080/insurance-service/getAllPlans
